<!-- deny the alumnis registration -->
<?php 
    // include db file
    include($_SERVER['DOCUMENT_ROOT'].'/config/database.php');
    // include php mailer to send mails
    include($_SERVER['DOCUMENT_ROOT'].'/config/phpmailer.php');
    // include alumni file
    include($_SERVER['DOCUMENT_ROOT'].'/models/alumni.php');
    // include college model fille
    include($_SERVER['DOCUMENT_ROOT'].'/models/college.php');

    // check if required get params are set
    if(isset($_GET['college_id']) && isset($_GET['department_id']) && isset($_GET['fullname']) && isset($_GET['phone']) && isset($_GET['id']) && isset($_GET['email']) && isset($_GET['dob']) && isset($_GET['roll_no'])){

        // database and model objs
        $connection = (new Database())->connect();
        $alumni = new Alumni($connection);

        $college_id = mysqli_real_escape_string($connection,$_GET['college_id']);
        $department_id = mysqli_real_escape_string($connection,$_GET['department_id']);
        $alumni_id = mysqli_real_escape_string($connection,$_GET['id']);
        $fullname = mysqli_real_escape_string($connection,$_GET['fullname']);
        $alumni_email = mysqli_real_escape_string($connection,$_GET['email']);
        
        // get all the alumni details before deleting it
        $alumni_details = $alumni->getUnverifiedAlumniDetailsById($alumni_id);

        // deny and delete alumni details from the table 
        $isDeletedSuccessfully = $alumni->denyNewRegistration($college_id,$department_id,$alumni_id);

        // check if deleted and send email to candidate with appropriate message why registration is denied
        if($isDeletedSuccessfully){

            // get college details by college id
            $college_details = (new College($connection))->getCollegeDetailsById($college_id);

            $college_name = $college_details['name'];
            $college_phone = $college_details['phone'];
            $college_email = $college_details['email'];
            $college_website = $college_details['website'];

            // email subject
            $email_subject ="
                Registration Denied By Admin - Alumni Portal
            ";
            // create email body to send
            $email_body = "
                <h4><b>Hey,</b> ".$fullname."</h4>
                <br>
                <p>Greetings from ".$college_name."</p> 
                <p>
                Thank you for registering on alumni portal !! we cannot confirm your identity please check your registration details properly and register again on alumni portal.
                once you register, your details will be verified by your college admin and you'll get your login credentials on registered email id (within 4- 5 working days)
                </p>
                <br>
                <h4>Following are your registration details : </h4>
                <p><b>College Name : </b>".$college_details['name']."</p>
                <p><b>Department Name : </b>".$alumni_details['department_name']."</p>
                <p><b>Name : </b>".$alumni_details['fullname']."</p>
                <p><b>Dob : </b>".$alumni_details['dob']."</p>
                <p><b>Email : </b>".$alumni_details['email']."</p>
                <p><b>Phone : </b>".$alumni_details['phone']."</p>
                <p><b>Roll_no : </b>".$alumni_details['roll_no']."</p>
                <p><b>Joining Year : </b>".$alumni_details['joining_year']."</p>
                <p><b>Passout Year : </b>".$alumni_details['passout_year']."</p>
                <p><b>CGPA : </b>".$alumni_details['cgpa']."</p>
                <p><b>Home Address : </b>".$alumni_details['home_address']."</p>
                <br>
                <p><b>NOTE: </b><mark>Please call your college admin if you do not get your login credentials within 4-5 working days</mark></p>
                
                Regards,
                <p><i>".$college_name."</i></p>
                <p><i>".$college_email.",</i></p> 
                <p><i>".$college_phone.",</i></p> 
                <p><i>".$college_website.",</i></p> 
                <br>
                Disclaimer: This is an autogenerated email please do not reply to this email
            ";
            $isHTML = true;
            // send mail to the alumni
            $isSent = sendMail($college_email,$college_name,$alumni_email,$fullname,$email_subject,$email_body,$isHTML);
            
            if($isSent){
                // redirect admin back to new registrations page
                // redirect admin back to new registrations page
                echo "
                    <script>
                        alert('Registration request denied successfully!!');
                        window.location.href = '/views/admin/new-registrations';
                    </script>
                "; 
            }else{
                echo "
                    <script>
                        alert('Registration request denied successfully!! but mail is not sent to alumni please inform the alumni with denied request');
                        window.location.href = '/views/admin/new-registrations';
                    </script>
                "; 
            }
        }else{

            // tell admin that something went wrong while denying
            echo "
                <script>
                    alert('Something went wrong while denying registration request please try again!!');
                    window.location.href = '/views/admin/new-registrations';
                </script>
            "; 
        }
    }else{
        header("Location: /views/admin");
    }


?>