<!-- verify the alumnis registration -->
<?php 
    // include db file
    include($_SERVER['DOCUMENT_ROOT'].'/config/database.php');
    // include php mailer to send mails
    include($_SERVER['DOCUMENT_ROOT'].'/config/phpmailer.php');
    // include alumni file
    include($_SERVER['DOCUMENT_ROOT'].'/models/alumni.php');
    // include college model
    include($_SERVER['DOCUMENT_ROOT'].'/models/college.php');

    // check if required get params are set
    if(isset($_GET['college_id']) && isset($_GET['department_id']) && isset($_GET['fullname']) && isset($_GET['phone']) && isset($_GET['id']) && isset($_GET['email']) && isset($_GET['dob']) && isset($_GET['roll_no'])){

        // database and model objs
        $connection = (new Database())->connect();
        $alumni = new Alumni($connection);

        // generate username and password
        // username => first_name+phone_last_four_digits
        // password => college_id+roll_no+dob(without dashes)
        $username = explode(' ',mysqli_real_escape_string($connection,$_GET['fullname']))[0].substr($_GET['phone'],-4);

        $password = md5(mysqli_real_escape_string($connection,$_GET['college_id']).mysqli_real_escape_string($connection,$_GET['roll_no']).explode('-',mysqli_real_escape_string($connection,$_GET['dob']))[0].explode('-',mysqli_real_escape_string($connection,$_GET['dob']))[1].explode('-',mysqli_real_escape_string($connection,$_GET['dob']))[2]);

        $college_id = mysqli_real_escape_string($connection,$_GET['college_id']);
        $department_id = mysqli_real_escape_string($connection,$_GET['department_id']);
        $alumni_id = mysqli_real_escape_string($connection,$_GET['id']);
        $fullname = mysqli_real_escape_string($connection,$_GET['fullname']);
        $alumni_email = mysqli_real_escape_string($connection,$_GET['email']);

        // verify and update username and password field with this 
        $isUpdatedSuccessfully = $alumni->verifyAndAcceptRegistration($college_id,$department_id,$alumni_id,$username,$password);

        // check if updated and send email to register candidate with username and password
        if($isUpdatedSuccessfully){
            // get college details by college id
            $college_details = (new College($connection))->getCollegeDetailsById($college_id);

            $college_name = $college_details['name'];
            $college_phone = $college_details['phone'];
            $college_email = $college_details['email'];
            $college_website = $college_details['website'];

            // email subject
            $email_subject ="
                Registration Confirmed!!!-Alumni Portal
            ";
            // create email body to send
            $email_body = "
                <h4><b>Hey,</b> ".$fullname."</h4>
                <br>
                <p>Greetings from ".$college_name."</p> 
                <p>Thank you for registering on alumni portal !! following is your login credentials.</p>
                <br>
                <h5><b>Username: </b>".$username."</h5>
                <h5><b>Password: </b>(combination of ".$college_id." + YOUR_ROLL_NO + DOB(eg. 1999-02-21 (without dashes)))</h5> 
                <br>
                <p><b>NOTE: </b><mark>Please Change your password once you login and do not share your username and password with anyone.</mark></p>
                
                Regards,
                <p><i>".$college_name."</i></p>
                <p><i>".$college_email.",</i></p> 
                <p><i>".$college_phone.",</i></p> 
                <p><i>".$college_website.",</i></p> 
                <br>
                Disclaimer: This is an autogenerated email please do not reply to this email
            ";
            $isHTML = true;
            // send mail to the alumni
            $isSent = sendMail($college_email,$college_name,$alumni_email,$fullname,$email_subject,$email_body,$isHTML);
            
            if($isSent){
                // redirect admin back to new registrations page
                echo "
                    <script>
                        alert('New registration verified and accepted successfully!!');
                        window.location.href = '/views/admin/new-registrations';
                    </script>
                "; 
            }else{
                echo "
                    <script>
                        alert('New registration verified and accepted successfully!! but mail is not sent to alumni please inform the alumni with login credentials');
                        window.location.href = '/views/admin/new-registrations';
                    </script>
                "; 
            }
        }else{

            // tell admin that something went wrong while verifying
            echo "
                <script>
                    alert('Something went wrong while verifying the alumni please try again!!');
                    window.location.href = '/views/admin/new-registrations';
                </script>
            "; 
        }
    }else{
        header("Location: /views/admin");
    }


?>